apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-opyi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-opyi@sha256:31cc2cedc7796286a99ad2ccbfda38dc3b5212ddafeb50849132f984dbbf9be4
        name: my-nodejs
        resources: {}
status: {}
